import { Room } from './room';

export const ROOMS: Room[] = [
  { id: 1, name: 'First Room',
    member_ids: [11, 12],
    blacklist: ['https://facebook.com'] },
  { id: 2, name: 'CSC301',
    member_ids: [11, 12],
    blacklist: ['https://facebook.com'] },
  { id: 3, name: 'Room #3',
    member_ids: [11, 12],
    blacklist: ['https://facebook.com'] },
  { id: 4, name: 'Room #4',
    member_ids: [11, 12],
    blacklist: ['https://facebook.com'] },
  { id: 5, name: 'Room #5',
    member_ids: [11, 12],
    blacklist: ['https://facebook.com'] },
  { id: 6, name: 'Room #6',
    member_ids: [11, 12],
    blacklist: ['https://facebook.com'] },
  { id: 7, name: 'Room #7',
    member_ids: [11, 12],
    blacklist: ['https://facebook.com'] },
  { id: 8, name: 'Room #8',
    member_ids: [11, 12],
    blacklist: ['https://facebook.com'] },
  { id: 9, name: 'Room #9',
    member_ids: [11, 12],
    blacklist: ['https://facebook.com'] },
  { id: 10, name: 'Room #10',
    member_ids: [13, 12],
    blacklist: ['https://facebook.com'] },
  { id: 11, name: 'CSC343',
    member_ids: [11, 12],
    blacklist: ['https://facebook.com'] }
];
